plugins {
    id 'com.gtnewhorizons.retrofuturagradle' version '1.4.9'
}

group = 'com.spatialshift'
version = '1.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

minecraft {
    mcVersion = '1.12.2'
    mcpMappingChannel = 'stable'
    mcpMappingVersion = '39'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

processResources {
    filteringCharset = 'UTF-8'
}
